# Generated by Django 4.1.3 on 2025-01-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triplocation',
            old_name='location_id',
            new_name='location',
        ),
    ]
