# Generated by Django 4.1.3 on 2025-01-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0002_location'),
        ('itineraryapi', '0002_travelmode'),
    ]

    operations = [
    ]
