# Generated by Django 4.1.3 on 2025-02-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0002_rename_location_id_triplocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='mode_of_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelMode', to='itineraryapi.travelmode'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTrips', to='itineraryapi.user'),
        ),
    ]
