# Generated by Django 4.1.3 on 2025-02-05 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0002_rename_location_id_triplocation_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='mode_of_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelMode', to='itineraryapi.travelmode'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTrips', to='itineraryapi.user'),
        ),
    ]
