# Generated by Django 4.1.3 on 2025-01-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0003_merge_0002_location_0002_travelmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripLocations', to='itineraryapi.location')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('number_of_travelers', models.IntegerField()),
                ('people_on_trip', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_of_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraryapi.travelmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraryapi.user')),
            ],
        ),
    ]
