# Generated by Django 4.1.3 on 2025-02-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraryapi', '0003_alter_trip_mode_of_travel_alter_trip_user'),
        ('itineraryapi', '0003_alter_trip_options_alter_trip_end_date_and_more'),
    ]

    operations = [
    ]
